/*
 * File: app/store/HerosStore.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobaApp.store.AbilitiesStore', {
    extend: 'Ext.ux.OfflineSyncStore',

    requires: [
        'MobaApp.model.Ability',
        'Ext.ux.OfflineSyncStore'
    ],

    config: {
        autoLoad: false,
        model: 'MobaApp.model.Ability',
        storeId: 'AbilitiesStore',
        localProxy: {
           type: 'localstorage',
           id: 'abilities-store'
        },
        serverProxy: {
           type: 'jsonp',
           url: 'http://api.mobawebapp.com/api/abilities/',
           reader: {
              type: 'json',
           }
        }

    }
});