/*
 * File: app/view/BuildPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobaApp.view.BuildPanel', {
    extend: 'Ext.Carousel',
    xtype:'herobuild',
    config: {
        items: [
            {
            //html : 'Stats',
            xtype: 'panel',
            scrollable: {
                direction: 'vertical'
            },
            tpl: new Ext.XTemplate(
                '<h1 class="title">Stats</h1>',
                '<tpl for="stats">',
                    '<div class="grid">',
                        '<div class="left">{key}</div>',
                        '<div class="right">{value}</div>',
                        '<div class="clear"></div>',
                    '</div>',
                '</tpl>'
                ),
            items: [{
                xtype:'button',
                margin: 10,
                text: 'Visit the complete guide at MobaFire.com',
                iconCls: 'action',
                iconMask: true,
                handler: function(){
                    window.open(this.getData().link)
                }
            }]
            },
            {
            xtype: 'panel',
            scrollable: {
                direction: 'vertical'
            },
            tpl: new Ext.XTemplate(
                '<h1 class="title">Runes</h1>',
                '<tpl for="runes">',
                    '<div class="grid">',
                        '<div class="left"><img src="{data.image}" width="40px">{data.name}</div>',
                        '<div class="right">{qty}</div>',
                        '<div class="clear"></div>',
                    '</div>',
                '</tpl>')
            },{
            xtype: 'panel',
            scrollable: {
                direction: 'vertical'
            },
            tpl: new Ext.XTemplate(
                '<h1 class="title">Masteries</h1>',
                '<tpl for="masteries">',
                    '<div class="grid">',
                        '<div class="left desc"><img src="{data.image}" width="40px">{data.description}</div>',
                        '<div class="right">{levels}</div>',
                        '<div class="clear"></div>',
                    '</div>',
                '</tpl>')
            },{
            xtype: 'panel',
            scrollable: {
                direction: 'vertical'
            },
            tpl: new Ext.XTemplate(
                '<h1 class="title">Items</h1>',
                '<tpl for="bags">',
                    '<div class="grid">',
                        '<div class="left desc">{name}<hr>',
                        '<tpl for="items">',
                        '<img src="{data.image}" width="70px" style="width:70px">',
                        '</tpl>',
                        '</div><div class="clear"></div>',
                    '</div>',
                '</tpl>')
            },{
            xtype: 'panel',
            scrollable: {
                direction: 'vertical'
            },
            tpl: new Ext.XTemplate(
                '<h1 class="title">Abilities</h1><table class="abilities" width="100%" cellpadding="10" cellspacing="10">',
                '<tr><tpl for="abilities">',
                '<td class="row"><img src="{data.image}" style="width: 70%; height: auto;"></td>',
                '</tpl></tr>',
                '<tpl for="levels">',
                '<tr>',
                '<tpl for="parent.abilities">',
                    '<td align="center"><div  class="{[values.levels.indexOf((parent+1).toString()) > -1 ? "on" : "off"]}">{[(parent+1).toString()]}</div></td>',
                '</tpl>',
                '</tr>',
                '</tpl>',
                '</table>')
            }
        ]
    }

});