/*
 * File: app/view/HeroView.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobaApp.view.HeroView', {
    extend: 'Ext.Container',
    alias: 'widget.heroview',
    xtype: 'heroview',
    config: {
        title: 'HeroName',
        id: 'HeroViewElm',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'list',
                id: 'BuildsView',
                plugins: [
                    {
                        xclass: 'Ext.plugin.PullRefresh',
                        pullRefreshText: 'Pull down to update list!'
                    },
                            {
                                xclass: 'Ext.plugin.ListPaging',
                                autoPaging: true,
                            }
                ],
                itemId: 'mylist1',
                itemTpl: [
                    '<div><img width="50px" height="50px" style="width:50px; height:50px" src="{heroimage}"> {title}</div>'
                ],
                store: 'BuildStore'
            }
        ]
    }

});