/*
 * File: app/model/Hero.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobaApp.model.Hero', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'name'
            },
            {
                name: 'riotPoints'
            },
            {
                name: 'influencePoints'
            },
            {
                name: 'image'
            },
            {
                name: 'tags'
            },
            {
                name: 'health'
            },
            {
                name: 'critical'
            },
            {
                name: 'mana'
            },
            {
                name: 'speed'
            },
            {
                name: 'armor'
            },
            {
                name: 'resist'
            },
            {
                name: 'healthRegen'
            },
            {
                name: 'manaRegen'
            },
            {
                name: 'attackRange'
            }
        ],hasMany  : {model: 'Build', name: 'builds'}
    }
});