/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true,
    paths: {
        'Ext.ux': 'ux'
    }
});


Ext.application({
    models: [
        'Hero',
        'Build',
        'Rune',
        'Item',
        'Mastery',
        'Ability',
        'Favorite'
    ],
    stores: [
        'HerosStore',
        'BuildStore',
        'RunesStore',
        'MasteryStore',
        'ItemsStore',
        'AbilitiesStore',
        'FavoritesStore'
    ],
    views: [
        'Main',
        'HeroView',
        'BuildPanel',
        'BuildSlider'
    ],
    controllers: [
        'HeroListController'
    ],
    requires: ['Ext.data.proxy.JsonP',"MobaApp.reader.Builds","Ext.field.Search","Ext.navigation.View","Ext.dataview.List",
    "Ext.MessageBox","Ext.Panel","Ext.plugin.ListPaging"
    ],
    name: 'MobaApp',

    launch: function() {

        Ext.create('MobaApp.view.Main', {fullscreen: true});
        //load and cache of runes
        if(localStorage.loaded != "true"){
            localStorage.loaded = true;
            var runes = Ext.create('MobaApp.store.RunesStore');
            runes.loadServer();

            var masteries = Ext.create('MobaApp.store.MasteryStore');
            masteries.loadServer();

            var items = Ext.create('MobaApp.store.ItemsStore');
            items.loadServer();

            var abilities = Ext.create('MobaApp.store.AbilitiesStore');
            abilities.loadServer();
        }
    }

});
